[env]
TERM = "xterm-256color"

[font]
size = 14.0

[window]
padding.x = 1
padding.y = 1

[font.bold]
family = "FiraCode"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
  # "~/.config/alacritty/themes/themes/carbonfox.toml"
  # "~/.config/alacritty/themes/themes/inferno.toml"

]
